apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: server-signalr
  name: server-signalr-svc
spec:
  ports:
    - name: 5678-80
      port: 5678
      protocol: TCP
      targetPort: 80
  selector:
    app: server-signalr
  type: ClusterIP
